<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputPath>bin\roslyn4.8\$(Configuration)\</OutputPath>
    <IntermediateOutputPath>obj\roslyn4.8\$(Configuration)\</IntermediateOutputPath>
    <RoslynApiVersion>4.8.0</RoslynApiVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <Import Project="ObjectAssertions.Build.targets" />

</Project>
